# Plain name lists fed into build_category.py to generate the full JSON records.
# Names should be real, Wikipedia-verifiable people/characters written as
# "First Last" (or "First Middle Last") so the game's two-word name rule works.

ATHLETE_BASE = ["Any Famous Person", "Athletes"]

BASKETBALL = ["Any Famous Person", "Athletes", "Basketball"]
FOOTBALL = ["Any Famous Person", "Athletes", "Football"]
HOCKEY = ["Any Famous Person", "Athletes", "Hockey"]
SOCCER = ["Any Famous Person", "Athletes", "Soccer"]
TENNIS = ["Any Famous Person", "Athletes", "Tennis"]
COMBAT = ["Any Famous Person", "Athletes", "Combat Sports"]
OLYMPICS = ["Any Famous Person", "Athletes", "Olympics / Track & Field"]
GOLF = ["Any Famous Person", "Athletes", "Golf"]
ACTORS = ["Any Famous Person", "Actors / Actresses"]
MUSICIANS = ["Any Famous Person", "Musicians"]
FICTIONAL = ["Any Famous Person", "Fictional Characters"]
POLITICIANS = ["Any Famous Person", "Politicians / Historical Figures"]

basketball_names = [
"LeBron James","Michael Jordan","Kobe Bryant","Magic Johnson","Larry Bird",
"Kareem Abdul-Jabbar","Wilt Chamberlain","Bill Russell","Shaquille ONeal","Tim Duncan",
"Kevin Durant","Stephen Curry","James Harden","Russell Westbrook","Chris Paul",
"Kawhi Leonard","Giannis Antetokounmpo","Nikola Jokic","Joel Embiid","Luka Doncic",
"Damian Lillard","Anthony Davis","Kyrie Irving","Klay Thompson","Draymond Green",
"Dwyane Wade","Carmelo Anthony","Dirk Nowitzki","Steve Nash","Allen Iverson",
"Vince Carter","Tracy McGrady","Paul Pierce","Ray Allen","Manu Ginobili",
"Tony Parker","Pau Gasol","Dwight Howard","Chris Bosh","Amare Stoudemire",
"Jason Kidd","Grant Hill","Reggie Miller","Gary Payton","John Stockton",
"Karl Malone","Charles Barkley","Patrick Ewing","Hakeem Olajuwon","David Robinson",
"Isiah Thomas","Dennis Rodman","Scottie Pippen","Clyde Drexler","George Gervin",
"Julius Erving","Moses Malone","Elgin Baylor","Oscar Robertson","Jerry West",
"Bob Cousy","John Havlicek","Rick Barry","Pete Maravich","Walt Frazier",
"Nate Archibald","Willis Reed","Dave Cowens","Bill Walton","James Worthy",
"Robert Parish","Kevin McHale","Dominique Wilkins","Alex English","Adrian Dantley",
"Bernard King","World B Free","Sidney Moncrief","Mark Aguirre","Jack Sikma",
"Artis Gilmore","Bob Lanier","Nate Thurmond","Wes Unseld","Dave Bing",
"Earl Monroe","Connie Hawkins","Spencer Haywood","Bob McAdoo","Alonzo Mourning",
"Gary Trent","Steve Francis","Baron Davis","Jason Williams","Stephon Marbury",
"Tracy Murray","Antawn Jamison","Shawn Marion","Rasheed Wallace","Ben Wallace",
"Chauncey Billups","Richard Hamilton","Rip Hamilton","Andre Iguodala","Luol Deng",
"Derrick Rose","Joakim Noah","Blake Griffin","DeAndre Jordan","Zach Randolph",
"Marc Gasol","Mike Conley","Rudy Gay","OJ Mayo","John Wall",
"Bradley Beal","Kemba Walker","DeMar DeRozan","Kyle Lowry","Jrue Holiday",
"Paul George","Jimmy Butler","Draymond Green","Klay Thompson","Andrew Wiggins",
"Ben Simmons","Trae Young","Zion Williamson","Ja Morant","Devin Booker",
"Donovan Mitchell","Jayson Tatum","Jaylen Brown","Bam Adebayo","Domantas Sabonis",
"Rudy Gobert","Karl-Anthony Towns","DeAaron Fox","Fred VanVleet","Pascal Siakam",
"Jamal Murray","Anthony Edwards","Shai Gilgeous-Alexander","Tyrese Haliburton","Victor Wembanyama",
"Brook Lopez","Robin Lopez","Deron Williams","Al Horford","Jeff Teague",
"Danny Green","PJ Tucker","Nicolas Batum","Boris Diaw","Tony Allen",
"Metta World Peace","Lamar Odom","Andrew Bynum","Danny Granger","Andre Miller",
"Elton Brand","Corey Maggette","Jermaine ONeal","Antoine Walker","Paul Pierce",
"Ray Allen","Kevin Garnett","Rasheed Wallace","Chris Webber","Jason Terry",
"Manu Ginobili","Peja Stojakovic","Vlade Divac","Dikembe Mutombo","Toni Kukoc",
"Drazen Petrovic","Arvydas Sabonis","Yao Ming","Dirk Nowitzki","Pau Gasol",
"Marc Gasol","Goran Dragic","Luka Doncic","Nikola Vucevic","Bojan Bogdanovic",
"Danilo Gallinari","Marco Belinelli","Nikola Jokic","Domantas Sabonis","Kristaps Porzingis",
"Giannis Antetokounmpo","Thanasis Antetokounmpo","Rudy Gobert","Evan Fournier","Tony Parker",
"Boris Diaw","Nicolas Batum","Ricky Rubio","Serge Ibaka","Al Jefferson",
"Andray Blatche","Josh Smith","Al Horford","DeMarcus Cousins","Kenneth Faried",
"Kentavious Caldwell-Pope","Harrison Barnes","Draymond Green","JaVale McGee","Andre Drummond",
"Hassan Whiteside","Marcin Gortat","Nikola Mirotic","Marvin Bagley","Jaren Jackson",
"De Aaron Fox","Buddy Hield","Malik Monk","Terrence Ross","Norman Powell",
"OG Anunoby","Jonathan Isaac","Mikal Bridges","Michael Porter","Deandre Ayton",
"Collin Sexton","Darius Garland","Cade Cunningham","Evan Mobley","Jalen Green",
"Scottie Barnes","Franz Wagner","Josh Giddey","Chet Holmgren","Paolo Banchero",
"Brandon Miller","Anthony Black","Amen Thompson","Ausar Thompson","Wembanyama Victor",
"Kevin Love","Klay Thompson","Steph Curry","Klay Thompson","Kevin Love",
"Danny Ainge","Robert Horry","Steve Kerr","John Paxson","Bill Cartwright",
"Horace Grant","Toni Kukoc","Luc Longley","Ron Harper","Dennis Scott",
"Nick Anderson","Anfernee Hardaway","Cedric Ceballos","Vlade Divac","Chris Webber",
"Latrell Sprewell","Tim Hardaway","Mitch Richmond","Chris Mullin","Sarunas Marciulionis",
"Rony Seikaly","Alaa Abdelnaby","Sam Perkins","Detlef Schrempf","Dale Ellis",
"Terry Cummings","Xavier McDaniel","Ricky Pierce","Nate McMillan","Gary Payton",
"Shawn Kemp","Vin Baker","Hersey Hawkins","Brent Barry","Rashard Lewis",
]

football_names = [
"Tom Brady","Peyton Manning","Joe Montana","Dan Marino","Aaron Rodgers",
"Patrick Mahomes","Drew Brees","Brett Favre","John Elway","Terry Bradshaw",
"Troy Aikman","Steve Young","Kurt Warner","Ben Roethlisberger","Eli Manning",
"Russell Wilson","Cam Newton","Deshaun Watson","Josh Allen","Lamar Jackson",
"Justin Herbert","Joe Burrow","Dak Prescott","Matthew Stafford","Jared Goff",
"Carson Wentz","Baker Mayfield","Trevor Lawrence","Kyler Murray","Jalen Hurts",
"Derek Carr","Ryan Tannehill","Philip Rivers","Matt Ryan","Jimmy Garoppolo",
"Andy Dalton","Alex Smith","Colin Kaepernick","Robert Griffin","Marcus Mariota",
"Jameis Winston","Blake Bortles","Nick Foles","Case Keenum","Mitchell Trubisky",
"Jerry Rice","Randy Moss","Terrell Owens","Larry Fitzgerald","Calvin Johnson",
"Antonio Brown","Julio Jones","DeAndre Hopkins","Odell Beckham","Davante Adams",
"Tyreek Hill","Justin Jefferson","CeeDee Lamb","Stefon Diggs","Cooper Kupp",
"Michael Thomas","Mike Evans","AJ Green","Julian Edelman","Wes Welker",
"Emmitt Smith","Walter Payton","Barry Sanders","Adrian Peterson","LaDainian Tomlinson",
"Marshall Faulk","Jim Brown","Eric Dickerson","Curtis Martin","Frank Gore",
"Derrick Henry","Christian McCaffrey","Saquon Barkley","Ezekiel Elliott","Nick Chubb",
"Alvin Kamara","Dalvin Cook","Todd Gurley","Le Veon Bell","Marion Barber",
"Reggie Bush","Priest Holmes","Shaun Alexander","Ricky Williams","Edgerrin James",
"Corey Dillon","Jerome Bettis","Thurman Thomas","Tony Dorsett","Franco Harris",
"OJ Simpson","Gale Sayers","Earl Campbell","Tony Gonzalez","Rob Gronkowski",
"Travis Kelce","Antonio Gates","Jason Witten","Shannon Sharpe","Kellen Winslow",
"George Kittle","Mark Andrews","Zach Ertz","Vernon Davis","Jimmy Graham",
"Reggie White","Bruce Smith","Lawrence Taylor","JJ Watt","Aaron Donald",
"Von Miller","Khalil Mack","TJ Watt","Myles Garrett","Nick Bosa",
"DeMarcus Ware","Julius Peppers","Michael Strahan","Derrick Thomas","Kevin Greene",
"Charles Haley","Richard Dent","Howie Long","Deacon Jones","Alan Page",
"Bob Lilly","Merlin Olsen","Randy White","Warren Sapp","John Randle",
"Ndamukong Suh","Fletcher Cox","Cameron Jordan","Chris Jones","Aaron Rodgers",
"Ray Lewis","Brian Urlacher","Patrick Willis","Luke Kuechly","Bobby Wagner",
"Zach Thomas","Junior Seau","Derrick Brooks","Sam Mills","Mike Singletary",
"Dick Butkus","Jack Lambert","Jack Ham","Willie Lanier","Bobby Bell",
"Deion Sanders","Rod Woodson","Darrell Green","Champ Bailey","Charles Woodson",
"Ronde Barber","Ty Law","Aqib Talib","Richard Sherman","Patrick Peterson",
"Jalen Ramsey","Stephon Gilmore","Xavien Howard","Marcus Peters","Jaire Alexander",
"Ed Reed","Troy Polamalu","Brian Dawkins","Ronnie Lott","Kenny Easley",
"Rodney Harrison","Earl Thomas","Eric Weddle","Devin McCourty","Tyrann Mathieu",
"Adam Vinatieri","Justin Tucker","Morten Andersen","Gary Anderson","Jason Elam",
"Ray Guy","Shane Lechler","Johnny Unitas","Bart Starr","Roger Staubach",
"Fran Tarkenton","Y A Tittle","Sonny Jurgensen","Sammy Baugh","Otto Graham",
"Norm Van Brocklin","Bobby Layne","Len Dawson","Ken Stabler","Dan Fouts",
"Jim Kelly","Warren Moon","Boomer Esiason","Vinny Testaverde","Rich Gannon",
"Jake Plummer","Donovan McNabb","Michael Vick","Vince Young","Matt Hasselbeck",
"Chad Pennington","David Garrard","Trent Green","Brad Johnson","Kerry Collins",
"Tarik Cohen","Devin Hester","Cordarrelle Patterson","Percy Harvin","Josh Cribbs",
"Deion Branch","Hines Ward","Steve Smith","Torry Holt","Isaac Bruce",
"Marvin Harrison","Reggie Wayne","Anquan Boldin","Steve Largent","Art Monk",
"Cris Carter","Andre Reed","Michael Irvin","Lynn Swann","John Stallworth",
"Paul Warfield","Charlie Joiner","Don Maynard","Raymond Berry","Fred Biletnikoff",
"Drew Pearson","Chad Ochocinco","Plaxico Burress","Anquan Boldin","Hakeem Nicks",
"Victor Cruz","Brandon Marshall","DeSean Jackson","Golden Tate","Amari Cooper",
"Keenan Allen","Mike Williams","Chris Godwin","Tyler Lockett","DK Metcalf",
"Ja Marr Chase","Amon Ra St Brown","Garrett Wilson","Puka Nacua","Nico Collins",
]

hockey_names = [
"Wayne Gretzky","Mario Lemieux","Bobby Orr","Gordie Howe","Sidney Crosby",
"Alexander Ovechkin","Mark Messier","Steve Yzerman","Jaromir Jagr","Patrick Roy",
"Martin Brodeur","Dominik Hasek","Terry Sawchuk","Ray Bourque","Nicklas Lidstrom",
"Scott Niedermayer","Denis Potvin","Bobby Hull","Phil Esposito","Guy Lafleur",
"Maurice Richard","Jean Beliveau","Henri Richard","Doug Harvey","Gump Worsley",
"Glenn Hall","Jacques Plante","Ken Dryden","Bernie Parent","Tony Esposito",
"Grant Fuhr","Patrick Kane","Jonathan Toews","Connor McDavid","Auston Matthews",
"Nathan MacKinnon","Leon Draisaitl","David Pastrnak","Nikita Kucherov","Steven Stamkos",
"Evgeni Malkin","Alex Ovechkin","Claude Giroux","Anze Kopitar","Drew Doughty",
"Erik Karlsson","Victor Hedman","Duncan Keith","PK Subban","Roman Josi",
"Cale Makar","Adam Fox","Quinn Hughes","Miro Heiskanen","Rasmus Dahlin",
"Igor Shesterkin","Andrei Vasilevskiy","Carey Price","Henrik Lundqvist","Tuukka Rask",
"Jonathan Quick","Braden Holtby","Marc-Andre Fleury","Sergei Bobrovsky","Connor Hellebuyck",
"Mats Sundin","Joe Sakic","Peter Forsberg","Teemu Selanne","Jari Kurri",
"Pavel Bure","Sergei Fedorov","Alexei Yashin","Ilya Kovalchuk","Alex Kovalev",
"Brett Hull","Luc Robitaille","Cam Neely","Pat LaFontaine","Adam Oates",
"Eric Lindros","Mike Modano","Brendan Shanahan","Chris Chelios","Al MacInnis",
"Paul Coffey","Larry Robinson","Denis Savard","Dale Hawerchuk","Marcel Dionne",
"Stan Mikita","Bobby Clarke","Darryl Sittler","Lanny McDonald","Rick Middleton",
"Bryan Trottier","Mike Bossy","Clark Gillies","Butch Goring","Billy Smith",
"Ron Hextall","Kirk McLean","Curtis Joseph","Ed Belfour","John Vanbiesbrouck",
"Chris Osgood","Mike Vernon","Felix Potvin","Andy Moog","Kelly Hrudey",
"Nikolai Khabibulin","Miikka Kiprusoff","Ryan Miller","Cory Schneider","Jaroslav Halak",
"Tim Thomas","Jonathan Bernier","Frederik Andersen","Ben Bishop","Pekka Rinne",
"Jack Eichel","Mitch Marner","William Nylander","Mikko Rantanen","Brayden Point",
"Jack Hughes","Elias Pettersson","Kirill Kaprizov","Matthew Tkachuk","Brady Tkachuk",
"Jake Guentzel","Tyler Seguin","Jamie Benn","John Tavares","Mark Scheifele",
"Blake Wheeler","Aleksander Barkov","Sam Reinhart","Jonathan Huberdeau","Zach Hyman",
"Filip Forsberg","Roman Josi","Ryan Nugent-Hopkins","Zach Werenski","Seth Jones",
"Charlie McAvoy","Rasmus Ristolainen","Jaccob Slavin","Dougie Hamilton","Morgan Rielly",
"Ivan Provorov","Shea Theodore","Josh Morrissey","Devon Toews","Bowen Byram",
"Owen Nolan","Keith Tkachuk","Brendan Morrow","Vincent Lecavalier","Martin St Louis",
"Daniel Alfredsson","Jason Spezza","Marian Hossa","Zdeno Chara","Chris Pronger",
"Scott Stevens","Rod Langway","Brian Leetch","Sergei Zubov","Kevin Lowe",
"Mark Howe","Borje Salming","Serge Savard","Guy Lapointe","Brad Park",
"Tim Horton","Red Kelly","Dit Clapper","Eddie Shore","Doug Bentley",
"Max Bentley","Ted Lindsay","Alex Delvecchio","Norm Ullman","Frank Mahovlich",
"Dave Keon","Johnny Bower","Terry Harper","Yvan Cournoyer","Jacques Lemaire",
"Steve Shutt","Larry Murphy","Sergei Makarov","Igor Larionov","Slava Fetisov",
"Alexander Mogilny","Valeri Kamensky","Sandis Ozolinsh","Petr Sykora","Milan Hejduk",
"Pavel Datsyuk","Nicklas Backstrom","Henrik Zetterberg","Daniel Sedin","Henrik Sedin",
"Marian Gaborik","Marian Hossa","Ilya Bryzgalov","Evgeni Nabokov","Dominik Hasek",
"Alexei Kovalev","Alexander Semin","Alex Ovechkin","Nicklas Lidstrom","Chris Chelios",
"Scott Stevens","Mark Messier","Steve Larmer","Jeremy Roenick","Doug Weight",
"Keith Tkachuk","Brendan Shanahan","Rob Blake","Chris Pronger","Ed Jovanovski",
"Bryan Berard","Jason Allison","Alexei Yashin","Daniel Alfredsson","Marian Hossa",
"Radek Bonk","Wade Redden","Zdeno Chara","Andrei Markov","Sheldon Souray",
"Mike Green","Kris Letang","Brent Burns","John Carlson","Torey Krug",
"Kris Draper","Darren McCarty","Igor Larionov","Vyacheslav Fetisov","Vladimir Konstantinov",
"Steve Yzerman","Brendan Shanahan","Sergei Fedorov","Nicklas Lidstrom","Chris Osgood",
"Jimmy Howard","Petr Mrazek","Jonathan Bernier","Anton Khudobin","Semyon Varlamov",
"Braden Holtby","Philipp Grubauer","Thatcher Demko","Jacob Markstrom","Linus Ullmark",
"Jeremy Swayman","Ilya Sorokin","Juuse Saros","Stuart Skinner","Jake Oettinger",
"Logan Thompson","Filip Gustavsson","Adin Hill","Vitek Vanecek","Casey DeSmith",
"Mika Zibanejad","Chris Kreider","Artemi Panarin","Adam Fox","Igor Shesterkin",
"Filip Chytil","Kaapo Kakko","Alexis Lafreniere","K'Andre Miller","Ryan Lindgren",
"Jack Roslovic","Boone Jenner","Kirill Marchenko","Patrik Laine","Pierre-Luc Dubois",
"Cole Sillinger","Zach Werenski","Adam Boqvist","Elvis Merzlikins","Sean Monahan",
]

soccer_names = [
"Lionel Messi","Cristiano Ronaldo","Pele Nascimento","Diego Maradona","Zinedine Zidane",
"Ronaldinho Gaucho","Ronaldo Nazario","Neymar Junior","Kylian Mbappe","Erling Haaland",
"Kevin De Bruyne","Robert Lewandowski","Luka Modric","Karim Benzema","Sergio Ramos",
"Andres Iniesta","Xavi Hernandez","Iker Casillas","Gianluigi Buffon","Manuel Neuer",
"Thibaut Courtois","Alisson Becker","Ederson Moraes","Virgil van Dijk","Sadio Mane",
"Mohamed Salah","Harry Kane","Son Heung-min","Bukayo Saka","Phil Foden",
"Jude Bellingham","Vinicius Junior","Rodrigo Hernandez","Frenkie de Jong","Pedri Gonzalez",
"Gavi Paez","Antoine Griezmann","Paul Pogba","Ngolo Kante","Raheem Sterling",
"Marcus Rashford","Bruno Fernandes","Jack Grealish","Declan Rice","Jordan Henderson",
"Wayne Rooney","Steven Gerrard","Frank Lampard","David Beckham","Paul Scholes",
"Ryan Giggs","Thierry Henry","Patrick Vieira","Didier Drogba","Samuel Eto'o",
"George Weah","Roberto Baggio","Alessandro Del Piero","Francesco Totti","Andrea Pirlo",
"Fabio Cannavaro","Paolo Maldini","Franco Baresi","Marco van Basten","Ruud Gullit",
"Frank Rijkaard","Dennis Bergkamp","Johan Cruyff","Ruud van Nistelrooy","Arjen Robben",
"Wesley Sneijder","Robin van Persie","Edwin van der Sar","Michael Ballack","Philipp Lahm",
"Bastian Schweinsteiger","Miroslav Klose","Thomas Muller","Toni Kroos","Mesut Ozil",
"Mario Gotze","Marco Reus","Joshua Kimmich","Leon Goretzka","Jamal Musiala",
"Xabi Alonso","David Silva","Sergio Aguero","Fernando Torres","David Villa",
"Cesc Fabregas","Gerard Pique","Jordi Alba","Marc-Andre ter Stegen","Ilkay Gundogan",
"Rodrygo Goes","Federico Valverde","Eden Hazard","Kevin Strootman","Romelu Lukaku",
"Christian Eriksen","Zlatan Ibrahimovic","Henrik Larsson","Freddie Ljungberg","Radamel Falcao",
"James Rodriguez","Juan Cuadrado","Carlos Valderrama","Gabriel Batistuta","Javier Zanetti",
"Diego Forlan","Luis Suarez","Edinson Cavani","Diego Godin","Alexis Sanchez",
"Arturo Vidal","Claudio Bravo","Hugo Sanchez","Rafael Marquez","Javier Hernandez",
"Andres Guardado","Carli Lloyd","Alex Morgan","Megan Rapinoe","Abby Wambach",
"Mia Hamm","Marta Vieira","Sam Kerr","Ada Hegerberg","Alexia Putellas",
"Aitana Bonmati","Vivianne Miedema","Wendie Renard","Lucy Bronze","Beth Mead",
"Ellen White","Fran Kirby","Rachel Daly","Millie Bright","Keira Walsh",
"Leah Williamson","Lauren James","Mary Earps","Chloe Kelly","Nikita Parris",
"George Best","Bobby Charlton","Bobby Moore","Gordon Banks","Geoff Hurst",
"Martin Peters","Kenny Dalglish","Ian Rush","Alan Shearer","Gary Lineker",
"Peter Shilton","Rio Ferdinand","John Terry","Ashley Cole","Gary Neville",
"Michael Owen","Emile Heskey","Robbie Fowler","Teddy Sheringham","Les Ferdinand",
"Andy Cole","Dwight Yorke","Jaap Stam","Roy Keane","Eric Cantona",
"Peter Schmeichel","Denis Irwin","Gary Pallister","Steve Bruce","Bryan Robson",
"Mark Hughes","Nemanja Vidic","Rio Ferdinand","Wes Brown","Patrice Evra",
"Antonio Valencia","Ashley Young","Juan Mata","Nemanja Matic","Fred Rodrigues",
"Marouane Fellaini","Anderson Silva Souza","Nani Sequeira","Park Ji-sung","Ander Herrera",
"Sergio Busquets","Luis Enrique","Pep Guardiola","Vicente Del Bosque","Jose Mourinho",
"Arsene Wenger","Carlo Ancelotti","Jurgen Klopp","Diego Simeone","Massimiliano Allegri",
"Antonio Conte","Zinedine Zidane","Julen Lopetegui","Thomas Tuchel","Hansi Flick",
"Didier Deschamps","Roberto Mancini","Luis de la Fuente","Gareth Southgate","Lionel Scaloni",
"Ruben Amorim","Xabi Alonso","Mikel Arteta","Erik ten Hag","Unai Emery",
"Ange Postecoglou","Enzo Maresca","Vincent Kompany","Roberto De Zerbi","Marco Silva",
"Kieran McKenna","Andoni Iraola","David Moyes","Eddie Howe","Sean Dyche",
"Steven Gerrard","Frank Lampard","Wayne Rooney","Patrick Vieira","Thierry Henry",
"Ruud Gullit","Marco van Basten","Louis van Gaal","Guus Hiddink","Bert van Marwijk",
"Rinus Michels","Johan Neeskens","Robin van Persie","Memphis Depay","Georginio Wijnaldum",
"Virgil van Dijk","Matthijs de Ligt","Nathan Ake","Denzel Dumfries","Cody Gakpo",
"Xherdan Shaqiri","Granit Xhaka","Manuel Akanji","Breel Embolo","Yann Sommer",
"Christian Pulisic","Weston McKennie","Tyler Adams","Gio Reyna","Yunus Musah",
"Landon Donovan","Clint Dempsey","Tim Howard","DaMarcus Beasley","Michael Bradley",
"Kaka Leite","Ronaldinho Gaucho","Rivaldo Ferreira","Roberto Carlos","Cafu Marques",
"Dida Nascimento","Julio Cesar","Thiago Silva","Marcelo Vieira","Dani Alves",
"Casemiro Henrique","Fabinho Tavares","Fred Rodrigues","Alisson Becker","Ederson Moraes",
"Gabriel Jesus","Richarlison Andrade","Raphinha Belloli","Antony Santos","Rodrygo Goes",
"Endrick Felipe","Vinicius Junior","Andres Iniesta","Xavi Hernandez","Sergio Busquets",
"Gerard Pique","Carles Puyol","Jordi Alba","Ivan Rakitic","Luis Suarez",
"Neymar Junior","Ousmane Dembele","Frenkie de Jong","Ronald Araujo","Pau Cubarsi",
"Robert Lewandowski","Jakub Blaszczykowski","Lukas Podolski","Manuel Neuer","Jerome Boateng",
"Mats Hummels","Antonio Rudiger","Niklas Sule","Kai Havertz","Serge Gnabry",
"Leroy Sane","Julian Brandt","Florian Wirtz","Jamal Musiala","Ilkay Gundogan",
"Karim Adeyemi","Niclas Fullkrug","Deniz Undav","Emre Can","Robin Gosens",
]

tennis_names = [
"Roger Federer","Rafael Nadal","Novak Djokovic","Andy Murray","Pete Sampras",
"Andre Agassi","Bjorn Borg","John McEnroe","Jimmy Connors","Rod Laver",
"Ken Rosewall","Ivan Lendl","Boris Becker","Stefan Edberg","Mats Wilander",
"Jim Courier","Michael Chang","Goran Ivanisevic","Pat Rafter","Lleyton Hewitt",
"Marat Safin","Juan Martin del Potro","Stan Wawrinka","Dominic Thiem","Daniil Medvedev",
"Alexander Zverev","Carlos Alcaraz","Jannik Sinner","Casper Ruud","Andrey Rublev",
"Nick Kyrgios","Grigor Dimitrov","Gael Monfils","David Ferrer","Tomas Berdych",
"David Nalbandian","Fernando Gonzalez","Nikolay Davydenko","Robin Soderling","Jo-Wilfried Tsonga",
"Richard Gasquet","Gilles Simon","Feliciano Lopez","Fabio Fognini","Marin Cilic",
"Kevin Anderson","John Isner","Milos Raonic","Denis Shapovalov","Felix Auger-Aliassime",
"Taylor Fritz","Frances Tiafoe","Tommy Paul","Ben Shelton","Holger Rune",
"Serena Williams","Venus Williams","Steffi Graf","Martina Navratilova","Chris Evert",
"Monica Seles","Billie Jean King","Margaret Court","Evonne Goolagong","Maria Sharapova",
"Justine Henin","Kim Clijsters","Amelie Mauresmo","Lindsay Davenport","Jennifer Capriati",
"Martina Hingis","Ana Ivanovic","Victoria Azarenka","Caroline Wozniacki","Angelique Kerber",
"Garbine Muguruza","Simona Halep","Naomi Osaka","Ashleigh Barty","Iga Swiatek",
"Aryna Sabalenka","Coco Gauff","Elena Rybakina","Jessica Pegula","Ons Jabeur",
"Karolina Pliskova","Petra Kvitova","Sloane Stephens","Sofia Kenin","Bianca Andreescu",
"Emma Raducanu","Barbora Krejcikova","Marketa Vondrousova","Madison Keys","Jelena Ostapenko",
"Suzanne Lenglen","Helen Wills","Alice Marble","Maureen Connolly","Doris Hart",
"Louise Brough","Shirley Fry","Althea Gibson","Maria Bueno","Darlene Hard",
"Nancy Richey","Rosie Casals","Virginia Wade","Chris Evert","Tracy Austin",
"Pam Shriver","Zina Garrison","Gabriela Sabatini","Arantxa Sanchez Vicario","Conchita Martinez",
"Mary Pierce","Anna Kournikova","Daniela Hantuchova","Nicole Vaidisova","Dinara Safina",
"Vera Zvonareva","Svetlana Kuznetsova","Elena Dementieva","Flavia Pennetta","Francesca Schiavone",
"Sara Errani","Roberta Vinci","Sabine Lisicki","Sara Sorribes Tormo","Belinda Bencic",
"Alize Cornet","Caroline Garcia","Kristina Mladenovic","Elina Svitolina","Dayana Yastremska",
"Rafael Osuna","Manuel Santana","Guillermo Vilas","Ilie Nastase","Adriano Panatta",
"Jan Kodes","Tomas Smid","Yannick Noah","Henri Leconte","Guy Forget",
"Cedric Pioline","Arnaud Clement","Fabrice Santoro","Sebastien Grosjean","Nicolas Mahut",
"Gilles Muller","Julien Benneteau","Gael Monfils","Jeremy Chardy","Adrian Mannarino",
"Ugo Humbert","Corentin Moutet","Arthur Fils","Giovanni Mpetshi Perricard","Terence Atmane",
"Manuel Orantes","Guillermo Coria","Gaston Gaudio","David Nalbandian","Juan Ignacio Chela",
"Jose Acasuso","Agustin Calleri","Mariano Puerta","Juan Monaco","Juan Martin del Potro",
"Leonardo Mayer","Diego Schwartzman","Guido Pella","Federico Delbonis","Francisco Cerundolo",
"Sebastian Baez","Tomas Martin Etcheverry","Facundo Bagnis","Nicolas Jarry","Cristian Garin",
"Alejandro Tabilo","Thiago Seyboth Wild","Thiago Monteiro","Joao Fonseca","Bernard Tomic",
"Nick Kyrgios","Alex de Minaur","Jordan Thompson","Thanasi Kokkinakis","Max Purcell",
"Marc Rosset","Roger Federer","Stan Wawrinka","Henri Laaksonen","Dominic Stricker",
"Robin Haase","Botic van de Zandschulp","Tallon Griekspoor","Jean-Julien Rojer","Wesley Koolhof",
"Jack Sock","Steve Johnson","Reilly Opelka","Mackenzie McDonald","Marcos Giron",
"Christopher Eubanks","Sebastian Korda","J J Wolf","Brandon Nakashima","Alex Michelsen",
"Learner Tien","Zizou Bergs","David Goffin","Kimmer Coppejans","Steve Darcis",
"Steven Diez","Felix Auger-Aliassime","Vasek Pospisil","Denis Shapovalov","Milos Raonic",
"Chris Eaton","Peter Polansky","Yoshihito Nishioka","Kei Nishikori","Taro Daniel",
"Shintaro Mochizuki","Yosuke Watanuki","Rinky Hijikata","Alexei Popyrin","James Duckworth",
"Marta Kostyuk","Dayana Yastremska","Anhelina Kalinina","Elina Svitolina","Lesia Tsurenko",
"Yulia Putintseva","Elena Rybakina","Zhang Shuai","Wang Qiang","Zheng Qinwen",
"Wang Xinyu","Shuai Zhang","Naomi Osaka","Nao Hibino","Misaki Doi",
"Camila Osorio","Emma Navarro","Peyton Stearns","Danielle Collins","Sofia Kenin",
"Beatriz Haddad Maia","Bia Haddad","Nadia Podoroska","Leylah Fernandez","Bianca Andreescu",
"Rebecca Marino","Genie Bouchard","Eugenie Bouchard","Katherine Sebov","Marina Stakusic",
"Diane Parry","Varvara Gracheva","Clara Burel","Elsa Jacquemot","Chloe Paquet",
"Fiona Ferro","Kristina Mladenovic","Alize Cornet","Oceane Dodin","Harmony Tan",
"Petra Martic","Donna Vekic","Ana Konjuh","Jelena Ostapenko","Anastasija Sevastova",
"Anett Kontaveit","Kaia Kanepi","Katerina Siniakova","Barbora Krejcikova","Karolina Muchova",
"Linda Noskova","Tereza Martincova","Sara Bejlek","Brenda Fruhvirtova","Anastasia Potapova",
"Veronika Kudermetova","Liudmila Samsonova","Daria Kasatkina","Ekaterina Alexandrova","Anna Blinkova",
"Mirra Andreeva","Diana Shnaider","Erika Andreeva","Polina Kudermetova","Maria Timofeeva",
]

combat_sports_names = [
"Muhammad Ali","Mike Tyson","Floyd Mayweather","Manny Pacquiao","Sugar Ray Robinson",
"Sugar Ray Leonard","Joe Frazier","George Foreman","Larry Holmes","Evander Holyfield",
"Lennox Lewis","Rocky Marciano","Jack Dempsey","Joe Louis","Roberto Duran",
"Marvin Hagler","Thomas Hearns","Oscar De La Hoya","Julio Cesar Chavez","Bernard Hopkins",
"Roy Jones","James Toney","Pernell Whitaker","Riddick Bowe","Michael Spinks",
"Ken Norton","Earnie Shavers","Ingemar Johansson","Sonny Liston","Gene Tunney",
"Max Schmeling","Ezzard Charles","Archie Moore","Willie Pep","Henry Armstrong",
"Carlos Monzon","Alexis Arguello","Salvador Sanchez","Wilfredo Gomez","Azumah Nelson",
"Naseem Hamed","Ricky Hatton","Amir Khan","Anthony Joshua","Tyson Fury",
"Deontay Wilder","Wladimir Klitschko","Vitali Klitschko","David Haye","Andre Ward",
"Gennady Golovkin","Canelo Alvarez","Terence Crawford","Errol Spence","Vasyl Lomachenko",
"Naoya Inoue","Katie Taylor","Claressa Shields","Laila Ali","Cecilia Braekhus",
"Georges St-Pierre","Anderson Silva","Jon Jones","Khabib Nurmagomedov","Conor McGregor",
"Israel Adesanya","Kamaru Usman","Charles Oliveira","Alexander Volkanovski","Islam Makhachev",
"Dustin Poirier","Justin Gaethje","Max Holloway","Alex Pereira","Leon Edwards",
"Sean Strickland","Dricus du Plessis","Colby Covington","Jorge Masvidal","Nate Diaz",
"Nick Diaz","BJ Penn","Matt Hughes","Randy Couture","Chuck Liddell",
"Tito Ortiz","Frank Mir","Brock Lesnar","Cain Velasquez","Fabricio Werdum",
"Junior dos Santos","Stipe Miocic","Daniel Cormier","Jan Blachowicz","Glover Teixeira",
"Demetrious Johnson","Henry Cejudo","Dominick Cruz","TJ Dillashaw","Cody Garbrandt",
"Aljamain Sterling","Sean O'Malley","Petr Yan","Jose Aldo","Frankie Edgar",
"Gilbert Melendez","Anthony Pettis","Rafael dos Anjos","Tony Ferguson","Kevin Lee",
"Amanda Nunes","Ronda Rousey","Miesha Tate","Holly Holm","Cris Cyborg",
"Valentina Shevchenko","Zhang Weili","Rose Namajunas","Joanna Jedrzejczyk","Carla Esparza",
"Antonio Rodrigo Nogueira","Wanderlei Silva","Mauricio Rua","Vitor Belfort","Rich Franklin",
"Hulk Hogan","Andre the Giant","Ric Flair","Stone Cold Steve Austin","The Rock Johnson",
"Undertaker Calaway","Shawn Michaels","Bret Hart","Randy Savage","Triple H",
"John Cena","Roman Reigns","Seth Rollins","Kurt Angle","Chris Jericho",
"Rey Mysterio","Eddie Guerrero","Edge Copeland","Batista Bautista","Brock Lesnar",
"Big Show Wight","Kane Jacobs","Mick Foley","Jeff Hardy","Matt Hardy",
"Christian Cage","Rob Van Dam","Jerry Lawler","Ric Flair","Sting Borden",
"Kevin Nash","Scott Hall","Diamond Dallas Page","Goldberg Bill","Booker T",
"Rikishi Fatu","Yokozuna Fatu","Big Van Vader","Bam Bam Bigelow","Ultimate Warrior",
"Jake Roberts","Bob Backlund","Bruno Sammartino","Pedro Morales","Superstar Graham",
"Sgt Slaughter","Iron Sheik Vaziri","Nikolai Volkoff","Greg Valentine","Don Muraco",
"Tito Santana","Jimmy Snuka","George Steele","Junkyard Dog","Koko B Ware",
"Honky Tonk Man","Million Dollar Man","Ted DiBiase","Big Boss Man","Akeem Layfield",
"Rick Rude","Curt Hennig","Bret Hart","Owen Hart","Jim Neidhart",
"British Bulldog Smith","Shawn Michaels","Diesel Nash","Razor Ramon","Vader Guerrero",
"Yokozuna Big","Lex Luger","Sid Vicious","Kevin Sullivan","Dusty Rhodes",
"Harley Race","Nick Bockwinkel","Verne Gagne","Lou Thesz","Gorgeous George",
"Antonio Inoki","Giant Baba","Jushin Liger","Mitsuharu Misawa","Kenta Kobashi",
"Kenny Omega","Kazuchika Okada","Hiroshi Tanahashi","Cody Rhodes","Dustin Rhodes",
"Matt Riddle","AJ Styles","Finn Balor","Samoa Joe","Kevin Owens",
"Sami Zayn","Bobby Lashley","Drew McIntyre","Sheamus O'Shaunessy","Randy Orton",
"Rey Fenix","Pentagon Jr","Will Ospreay","Adam Cole","Bryan Danielson",
"Chris Hero","Claudio Castagnoli","Jon Moxley","MJF Friedman","Darby Allin",
"Katsuyori Shibata","Tomohiro Ishii","Zack Sabre Jr","Shingo Takagi","Hiromu Takahashi",
"Deontay Wilder","Anthony Joshua","Oleksandr Usyk","Errol Spence","Terence Crawford",
"Devin Haney","Ryan Garcia","Gervonta Davis","Shakur Stevenson","Naoya Inoue",
"Canelo Alvarez","David Benavidez","Jermall Charlo","Jermell Charlo","Caleb Plant",
"Gene Tunney","Jersey Joe Walcott","Jimmy Braddock","Max Baer","Tommy Loughran",
"Primo Carnera","Ingemar Johansson","Floyd Patterson","Cassius Clay","Ken Norton",
"Leon Spinks","Michael Spinks","Buster Douglas","Michael Moorer","Chris Byrd",
"Hasim Rahman","John Ruiz","Nikolai Valuev","Ruslan Chagaev","Sergei Kovalev",
"Artur Beterbiev","Dmitry Bivol","Joshua Buatsi","Anthony Yarde","Callum Smith",
"Josh Taylor","Jose Ramirez","Regis Prograis","Jaron Ennis","Keith Thurman",
"Danny Garcia","Adrien Broner","Mikey Garcia","Leo Santa Cruz","Abner Mares",
"Nonito Donaire","Guillermo Rigondeaux","Carl Frampton","Scott Quigg","Lee Selby",
"Josh Warrington","George Kambosos","Teofimo Lopez","Devin Haney","Vasyl Lomachenko",
"Oscar Valdez","Shakur Stevenson","Emanuel Navarrete","Luis Nery","Naoya Inoue",
"Roman Gonzalez","Juan Francisco Estrada","Srisaket Sor Rungvisai","Donnie Nietes","Zolani Tete",
"Frampton Carl","Josh Kelly","Conor Benn","Chris Eubank","Chris Eubank Jr",
"Nigel Benn","Michael Watson","Naseem Hamed","Ricky Burns","Kell Brook",
"Amir Khan","David Haye","Tony Bellew","George Groves","James DeGale",
"Carl Froch","Joe Calzaghe","Ricky Hatton","Junior Witter","Kevin Mitchell",
]

olympics_track_names = [
"Usain Bolt","Carl Lewis","Jesse Owens","Michael Phelps","Mark Spitz",
"Simone Biles","Nadia Comaneci","Larisa Latynina","Katie Ledecky","Florence Griffith-Joyner",
"Jackie Joyner-Kersee","Wilma Rudolph","Allyson Felix","Michael Johnson","Edwin Moses",
"Sebastian Coe","Steve Ovett","Haile Gebrselassie","Kenenisa Bekele","Mo Farah",
"Eliud Kipchoge","Emil Zatopek","Paavo Nurmi","Sergey Bubka","Renaud Lavillenie",
"Bob Beamon","Mike Powell","Javier Sotomayor","Yelena Isinbayeva","Marion Jones",
"Gail Devers","Merlene Ottey","Shelly-Ann Fraser-Pryce","Elaine Thompson-Herah","Shericka Jackson",
"Yohan Blake","Justin Gatlin","Tyson Gay","Andre De Grasse","Noah Lyles",
"Wayde van Niekerk","Kirani James","LaShawn Merritt","Jeremy Wariner","Christian Coleman",
"Trayvon Bromell","Fred Kerley","Christian Taylor","Ryan Crouser","Joe Kovacs",
"Ashton Eaton","Damian Warner","Kevin Mayer","Bryan Clay","Roman Sebrle",
"Dan O'Brien","Bruce Jenner","Rafer Johnson","Bob Mathias","Daley Thompson",
"Michael Groves","Ryan Lochte","Caeleb Dressel","Adam Peaty","Ian Thorpe",
"Grant Hackett","Kieren Perkins","Alexander Popov","Matt Biondi","Gary Hall",
"Janet Evans","Amy Van Dyken","Dara Torres","Natalie Coughlin","Missy Franklin",
"Rebecca Adlington","Federica Pellegrini","Sarah Sjostrom","Katinka Hosszu","Sun Yang",
"Nathan Chen","Yuzuru Hanyu","Evgeni Plushenko","Scott Hamilton","Brian Boitano",
"Michelle Kwan","Kristi Yamaguchi","Peggy Fleming","Dorothy Hamill","Torvill and Dean",
"Apolo Ohno","Shani Davis","Bonnie Blair","Eric Heiden","Dan Jansen",
"Lindsey Vonn","Mikaela Shiffrin","Picabo Street","Bode Miller","Ted Ligety",
"Shaun White","Chloe Kim","Lindsey Jacobellis","Kelly Clark","Jamie Anderson",
"Ryan Suter","Sasha Cohen","Johnny Weir","Mao Asada","Jason Brown",
"Gabby Douglas","Aly Raisman","McKayla Maroney","Shawn Johnson","Mary Lou Retton",
"Kerri Strug","Dominique Dawes","Sunisa Lee","Jordan Chiles","Jade Carey",
"Kyla Ross","Laurie Hernandez","Nastia Liukin","Carly Patterson","Vitaly Scherbo",
"Alexei Nemov","Kohei Uchimura","Max Whitlock","Louis Smith","Oksana Chusovitina",
"Svetlana Khorkina","Aliya Mustafina","Simona Amanar","Andreea Raducan","Lilia Podkopayeva",
"Sydney McLaughlin","Athing Mu","Gabby Thomas","Sha'Carri Richardson","Dina Asher-Smith",
"Dafne Schippers","Caster Semenya","Faith Kipyegon","Sifan Hassan","Genzebe Dibaba",
"Almaz Ayana","Tirunesh Dibaba","Meseret Defar","Vivian Cheruiyot","Hicham El Guerrouj",
"Kipchoge Keino","Lasse Viren","Steve Prefontaine","Jim Ryun","Frank Shorter",
"Bill Rodgers","Alberto Salazar","Joan Benoit","Grete Waitz","Ingrid Kristiansen",
"Paula Radcliffe","Tegla Loroupe","Catherine Ndereba","Brigid Kosgei","Ruth Chepngetich",
"Peres Jepchirchir","Eliud Kipchoge","Kelvin Kiptum","Wilson Kipsang","Dennis Kimetto",
"Geoffrey Mutai","Abel Kirui","Sammy Wanjiru","Robert Kiplagat Cheruiyot","Moses Tanui",
"Derartu Tulu","Fatuma Roba","Gete Wami","Berhane Adere","Almaz Ayana",
"Genzebe Dibaba","Bekele Kenenisa","Mo Farah","Galen Rupp","Bernard Lagat",
"Matthew Centrowitz","Jenny Simpson","Shalane Flanagan","Deena Kastor","Molly Seidel",
"Emily Sisson","Keira DAmato","Des Linden","Meb Keflezighi","Ryan Hall",
"Dathan Ritzenhein","Chris Solinsky","Galen Rupp","Evan Jager","Donavan Brazier",
"Nick Symmonds","Matthew Boling","Erriyon Knighton","Kenny Bednarek","Marvin Bracy",
"Christian Coleman","Michael Norman","Rai Benjamin","Grant Holloway","Devon Allen",
"Karsten Warholm","Rasmus Magi","Alison Dos Santos","Warholm Karsten","Yulimar Rojas",
"Caterine Ibarguen","Mihail Solomon","Miltiadis Tentoglou","Malaika Mihambo","Ivana Vuleta",
"Valarie Allman","Sandra Perkovic","Yaime Perez","Sarah Mitton","Chase Ealey",
"Ryan Crouser","Joe Kovacs","Tomas Walsh","Nick Ponzio","Payton Otterdahl",
"Anderson Peters","Neeraj Chopra","Johannes Vetter","Julian Weber","Jakub Vadlejch",
"Duplantis Armand","Sam Kendricks","Christopher Nilsen","Ernest Obiena","Piotr Lisek",
"Nafissatou Thiam","Katarina Johnson-Thompson","Anouk Vetter","Carolin Schafer","Adrianna Sulek",
"Damian Warner","Kevin Mayer","Pierce LePage","Zach Ziemek","Ashton Eaton",
"Katie McLaughlin","Ryan Held","Nathan Adrian","Cullen Jones","Anthony Ervin",
"Simone Manuel","Lilly King","Regan Smith","Kate Douglass","Torri Huske",
"Gretchen Walsh","Claire Curzan","Katie Grimes","Bobby Finke","Carson Foster",
"Hunter Armstrong","Ryan Murphy","Nic Fink","Michael Andrew","Chase Kalisz",
]

golf_names = [
"Tiger Woods","Jack Nicklaus","Arnold Palmer","Gary Player","Tom Watson",
"Sam Snead","Ben Hogan","Byron Nelson","Walter Hagen","Bobby Jones",
"Gene Sarazen","Lee Trevino","Nick Faldo","Seve Ballesteros","Greg Norman",
"Nick Price","Ernie Els","Vijay Singh","Phil Mickelson","Rory McIlroy",
"Jordan Spieth","Justin Thomas","Brooks Koepka","Dustin Johnson","Jon Rahm",
"Scottie Scheffler","Xander Schauffele","Patrick Cantlay","Collin Morikawa","Viktor Hovland",
"Bryson DeChambeau","Justin Rose","Adam Scott","Henrik Stenson","Sergio Garcia",
"Padraig Harrington","Martin Kaymer","Graeme McDowell","Rickie Fowler","Matt Kuchar",
"Webb Simpson","Zach Johnson","Keegan Bradley","Bubba Watson","Charl Schwartzel",
"Louis Oosthuizen","Danny Willett","Francesco Molinari","Shane Lowry","Cameron Smith",
"Hideki Matsuyama","Si Woo Kim","Tommy Fleetwood","Tyrrell Hatton","Ian Poulter",
"Lee Westwood","Colin Montgomerie","Darren Clarke","David Duval","Davis Love",
"Fred Couples","Curtis Strange","Hale Irwin","Johnny Miller","Tom Kite",
"Larry Nelson","Andy North","Craig Stadler","Mark OMeara","Paul Azinger",
"Corey Pavin","Payne Stewart","Steve Elkington","Nick Watney","Bill Haas",
"Jim Furyk","David Toms","Chad Campbell","Charles Howell","Ryan Moore",
"Kevin Kisner","Kevin Na","Brian Harman","Max Homa","Sam Burns",
"Cameron Young","Wyndham Clark","Rickie Fowler","Sungjae Im","Tom Hoge",
"Sahith Theegala","Denny McCarthy","Russell Henley","Chris Kirk","Emiliano Grillo",
"Byeong Hun An","Corey Conners","Adam Hadwin","Mackenzie Hughes","Taylor Pendrith",
"Annika Sorenstam","Lorena Ochoa","Se Ri Pak","Inbee Park","Nelly Korda",
"Lydia Ko","Stacy Lewis","Michelle Wie","Paula Creamer","Cristie Kerr",
"Karrie Webb","Laura Davies","Juli Inkster","Betsy King","Nancy Lopez",
"Patty Berg","Mickey Wright","Kathy Whitworth","JoAnne Carner","Babe Zaharias",
"Louise Suggs","Amy Alcott","Meg Mallon","Beth Daniel","Pat Bradley",
"So Yeon Ryu","Sung Hyun Park","Ariya Jutanugarn","Minjee Lee","Jin Young Ko",
"Brooke Henderson","Danielle Kang","Lexi Thompson","Charley Hull","Georgia Hall",
"Byron Nelson","Sam Snead","Cary Middlecoff","Julius Boros","Billy Casper",
"Doug Ford","Tommy Bolt","Dow Finsterwald","Jack Burke","Art Wall",
"Ken Venturi","Bobby Nichols","Gay Brewer","Bob Goalby","George Archer",
"Orville Moody","Chi-Chi Rodriguez","Bruce Crampton","Lanny Wadkins","Andy Bean",
"Jerry Pate","John Mahaffey","Bill Rogers","Ray Floyd","Calvin Peete",
"Craig Stadler","Larry Mize","Sandy Lyle","Mark Calcavecchia","Wayne Grady",
"Ian Baker-Finch","John Daly","Steve Elkington","Mark Brooks","Lee Janzen",
"Justin Leonard","Davis Love","Stewart Cink","Todd Hamilton","Michael Campbell",
"Geoff Ogilvy","Angel Cabrera","Trevor Immelman","Zach Johnson","Lucas Glover",
"Graeme McDowell","Webb Simpson","Jordan Spieth","Dustin Johnson","Brooks Koepka",
"Gary Woodland","Bryson DeChambeau","Jon Rahm","Matt Fitzpatrick","Wyndham Clark",
"Brian Harman","Xander Schauffele","Bryson DeChambeau","Scottie Scheffler","Rory McIlroy",
"Sepp Straka","Ludvig Aberg","Akshay Bhatia","Nick Dunlap","Neal Shipley",
"Tom Weiskopf","Billy Andrade","Fred Funk","Jesper Parnevik","Retief Goosen",
"Vijay Singh","Nick Price","Trevor Immelman","Ernie Els","Charl Schwartzel",
"Branden Grace","Louis Oosthuizen","Justin Harding","Christiaan Bezuidenhout","Dean Burmester",
"Thomas Pieters","Nicolas Colsaerts","Joost Luiten","Matthieu Pavon","Victor Perez",
"Robert MacIntyre","Matt Wallace","Aaron Rai","Tommy Fleetwood","Justin Rose",
"Paul Casey","Tyrrell Hatton","Danny Willett","Ross Fisher","Chris Wood",
"Se Ri Pak","Grace Park","Christina Kim","Angela Park","Jane Park",
"Amy Yang","In Gee Chun","Sei Young Kim","Hyo Joo Kim","Eun-Hee Ji",
"Chella Choi","I K Kim","Jenny Shin","Ha Na Jang","Hye-Jin Choi",
"A Lim Kim","Youngin Chun","Ayaka Furue","Hinako Shibuno","Nasa Hataoka",
"Sakura Yokomine","Ai Miyazato","Yani Tseng","Candie Kung","Ssu-Chia Cheng",
"Cheyenne Woods","Lucy Li","Alison Lee","Rose Zhang","Yealimi Noh",
"Harry Vardon","J H Taylor","James Braid","Tommy Armour","Horton Smith",
"Ralph Guldahl","Lawson Little","Craig Wood","Vic Ghezzi","Lloyd Mangrum",
"Herman Keiser","Jimmy Demaret","Claude Harmon","Jack Burke Jr","Bob Rosburg",
"Jerry Barber","Jack Fleck","Dick Mayer","Bob Charles","Al Geiberger",
"Bruce Devlin","Bob Murphy","Miller Barber","Gene Littler","Frank Beard",
"Dave Stockton","Charles Coody","Lou Graham","David Graham","Wayne Levi",
"Hubert Green","Scott Simpson","Y E Yang","Lucas Herbert","Adam Long",
"Chesson Hadley","Doc Redman","Cameron Champ","Beau Hossler","Aaron Wise",
"Joel Dahmen","Harris English","Patrick Rodgers","J T Poston","Andrew Putnam",
"Adam Schenk","Lanto Griffin","Talor Gooch","Harold Varner","Cameron Davis",
"Matt NeSmith","Trey Mullinax","Doug Ghim","Justin Suh","Davis Riley",
"Nick Hardy","Chandler Phillips","Vince Whaley","Ben Griffin","Peter Malnati",
"Nick Taylor","Adam Svensson","David Lipsky","Kevin Streelman","Brendon Todd",
]

actors_names = [
"Tom Hanks","Denzel Washington","Leonardo DiCaprio","Brad Pitt","Robert De Niro",
"Al Pacino","Jack Nicholson","Morgan Freeman","Anthony Hopkins","Daniel Day-Lewis",
"Gary Oldman","Christian Bale","Joaquin Phoenix","Russell Crowe","Sean Penn",
"Kevin Spacey","Tom Cruise","Will Smith","Johnny Depp","Matt Damon",
"Ben Affleck","George Clooney","Samuel Jackson","Harrison Ford","Clint Eastwood",
"Robin Williams","Dustin Hoffman","Jeff Bridges","Michael Douglas","Kevin Costner",
"Matthew McConaughey","Christoph Waltz","Mahershala Ali","Casey Affleck","Rami Malek",
"Gary Sinise","John Malkovich","Willem Dafoe","Ralph Fiennes","Colin Firth",
"Eddie Redmayne","Benedict Cumberbatch","Idris Elba","Chiwetel Ejiofor","David Oyelowo",
"Michael Fassbender","Tom Hardy","Cillian Murphy","Ryan Gosling","Ryan Reynolds",
"Chris Evans","Chris Hemsworth","Chris Pratt","Robert Downey","Mark Ruffalo",
"Paul Rudd","Jeremy Renner","Jason Statham","Vin Diesel","Dwayne Johnson",
"Liam Neeson","Pierce Brosnan","Daniel Craig","Timothy Dalton","Roger Moore",
"Sean Connery","Hugh Jackman","Patrick Stewart","Ian McKellen","Alan Rickman",
"Jude Law","Ewan McGregor","Orlando Bloom","Viggo Mortensen","Sam Neill",
"Jeff Goldblum","Bill Murray","Steve Carell","Jim Carrey","Adam Sandler",
"Ben Stiller","Owen Wilson","Vince Vaughn","Will Ferrell","Seth Rogen",
"Jonah Hill","Steve Martin","Eddie Murphy","Chris Rock","Kevin Hart",
"Denzel Curry","Forest Whitaker","Terrence Howard","Don Cheadle","Laurence Fishburne",
"Wesley Snipes","Ice Cube","Ice T","LL Cool J","Common Lynn",
"Meryl Streep","Cate Blanchett","Nicole Kidman","Julia Roberts","Sandra Bullock",
"Charlize Theron","Kate Winslet","Frances McDormand","Emma Thompson","Judi Dench",
"Helen Mirren","Glenn Close","Susan Sarandon","Jodie Foster","Sigourney Weaver",
"Michelle Pfeiffer","Julianne Moore","Naomi Watts","Reese Witherspoon","Amy Adams",
"Jessica Chastain","Natalie Portman","Scarlett Johansson","Anne Hathaway","Emma Stone",
"Jennifer Lawrence","Jennifer Aniston","Angelina Jolie","Halle Berry","Viola Davis",
"Octavia Spencer","Lupita Nyong'o","Zoe Saldana","Gal Gadot","Margot Robbie",
"Emily Blunt","Kate Beckinsale","Rachel Weisz","Keira Knightley","Emma Watson",
"Saoirse Ronan","Florence Pugh","Elizabeth Olsen","Brie Larson","Michelle Williams",
"Amy Poehler","Tina Fey","Kristen Wiig","Melissa McCarthy","Kristen Bell",
"Anna Kendrick","Mila Kunis","Olivia Wilde","Blake Lively","Rachel McAdams",
"Rebecca Ferguson","Alicia Vikander","Vera Farmiga","Marion Cotillard","Penelope Cruz",
"Javier Bardem","Antonio Banderas","Salma Hayek","Gael Garcia Bernal","Diego Luna",
"Benicio Del Toro","Oscar Isaac","Andy Garcia","John Leguizamo","Edward Norton",
"Philip Seymour Hoffman","Heath Ledger","James Franco","Joseph Gordon-Levitt","Miles Teller",
"Andrew Garfield","Tom Holland","Zendaya Coleman","Timothee Chalamet","Austin Butler",
"Paul Dano","Adam Driver","Oscar Isaac","John Boyega","Daisy Ridley",
"Charlie Chaplin","Buster Keaton","Humphrey Bogart","Cary Grant","James Stewart",
"Henry Fonda","Gregory Peck","Marlon Brando","Paul Newman","Steve McQueen",
"Sidney Poitier","James Dean","Gary Cooper","John Wayne","Spencer Tracy",
"Charlton Heston","Kirk Douglas","Burt Lancaster","Anthony Quinn","Peter OToole",
"Richard Burton","Michael Caine","Sean Connery","Roger Moore","David Niven",
"Rex Harrison","Alec Guinness","Laurence Olivier","Ralph Richardson","John Gielgud",
"Orson Welles","Peter Sellers","Rowan Atkinson","John Cleese","Eric Idle",
"Terry Gilliam","Michael Palin","Graham Chapman","Terry Jones","Hugh Laurie",
"Stephen Fry","Emma Thompson","Kenneth Branagh","Tom Wilkinson","Jim Broadbent",
"Bill Nighy","Geoffrey Rush","Russell Crowe","Hugh Jackman","Guy Pearce",
"Eric Bana","Sam Worthington","Chris Hemsworth","Liam Hemsworth","Joel Edgerton",
"Nicole Kidman","Cate Blanchett","Naomi Watts","Rachel Griffiths","Toni Collette",
"Isla Fisher","Rebel Wilson","Margot Robbie","Rose Byrne","Portia de Rossi",
"Marlee Matlin","Marisa Tomei","Renee Zellweger","Elisabeth Shue","Winona Ryder",
"Christina Ricci","Claire Danes","Kirsten Dunst","Drew Barrymore","Cameron Diaz",
"Lucy Liu","Michelle Yeoh","Zhang Ziyi","Gong Li","Maggie Cheung",
"Tony Leung","Chow Yun-fat","Jet Li","Jackie Chan","Bruce Lee",
"Donnie Yen","Sammo Hung","Yuen Biao","Andy Lau","Aaron Kwok",
"Leon Lai","Takeshi Kaneshiro","Rain Jung","Song Kang-ho","Choi Min-sik",
"Lee Byung-hun","Bae Doona","Kim Min-hee","Youn Yuh-jung","Ken Watanabe",
"Hiroyuki Sanada","Rinko Kikuchi","Tadanobu Asano","Takeshi Kitano","Toshiro Mifune",
"Akira Kurosawa","Federico Fellini","Marcello Mastroianni","Sophia Loren","Anna Magnani",
"Roberto Benigni","Monica Bellucci","Isabella Rossellini","Gina Lollobrigida","Vittorio Gassman",
"Gerard Depardieu","Jean Reno","Vincent Cassel","Marion Cotillard","Audrey Tautou",
"Juliette Binoche","Isabelle Huppert","Catherine Deneuve","Brigitte Bardot","Alain Delon",
"Jean-Paul Belmondo","Louis de Funes","Pierre Richard","Omar Sy","Eva Green",
"Melanie Laurent","Ludivine Sagnier","Sophie Marceau","Vincent Lindon","Daniel Auteuil",
"Diane Keaton","Woody Allen","Mia Farrow","Owen Wilson","Rachel Brosnahan",
"Timothee Chalamet","Florence Pugh","Anya Taylor-Joy","Barry Keoghan","Paul Mescal",
"Jacob Elordi","Sydney Sweeney","Jenna Ortega","Millie Bobby Brown","Finn Wolfhard",
"Noah Schnapp","Gaten Matarazzo","Caleb McLaughlin","Sadie Sink","Winona Ryder",
]

musicians_names = [
"Elvis Presley","Michael Jackson","Prince Nelson","David Bowie","Freddie Mercury",
"John Lennon","Paul McCartney","George Harrison","Ringo Starr","Bob Dylan",
"Jimi Hendrix","Bob Marley","Whitney Houston","Mariah Carey","Celine Dion",
"Madonna Ciccone","Beyonce Knowles","Rihanna Fenty","Taylor Swift","Adele Adkins",
"Ed Sheeran","Bruno Mars","Justin Timberlake","Justin Bieber","Ariana Grande",
"Billie Eilish","Olivia Rodrigo","Dua Lipa","Harry Styles","Sam Smith",
"Lady Gaga","Katy Perry","Kelly Clarkson","Christina Aguilera","Britney Spears",
"Shakira Mebarak","Jennifer Lopez","Selena Quintanilla","Gloria Estefan","Marc Anthony",
"Kanye West","Jay-Z Carter","Eminem Mathers","Snoop Dogg","Dr Dre",
"Tupac Shakur","Notorious BIG","Nas Jones","Kendrick Lamar","Drake Graham",
"Travis Scott","Post Malone","Cardi B","Nicki Minaj","Lizzo Jefferson",
"Chance The Rapper","J Cole","Lil Wayne","50 Cent","Ludacris Bridges",
"Missy Elliott","Queen Latifah","LL Cool J","Run DMC","Public Enemy",
"Frank Sinatra","Dean Martin","Sammy Davis","Tony Bennett","Nat King Cole",
"Ella Fitzgerald","Billie Holiday","Louis Armstrong","Duke Ellington","Miles Davis",
"John Coltrane","Charlie Parker","Dizzy Gillespie","Thelonious Monk","Ray Charles",
"Aretha Franklin","Stevie Wonder","Marvin Gaye","Diana Ross","James Brown",
"Otis Redding","Sam Cooke","Al Green","Curtis Mayfield","Smokey Robinson",
"Chuck Berry","Little Richard","Buddy Holly","Roy Orbison","Johnny Cash",
"Willie Nelson","Dolly Parton","Kenny Rogers","Garth Brooks","Shania Twain",
"George Strait","Reba McEntire","Tim McGraw","Faith Hill","Carrie Underwood",
"Keith Urban","Blake Shelton","Miranda Lambert","Luke Bryan","Chris Stapleton",
"Kacey Musgraves","Zach Bryan","Morgan Wallen","Eric Church","Jason Aldean",
"Led Zeppelin","Robert Plant","Jimmy Page","Pink Floyd","Roger Waters",
"David Gilmour","The Who","Pete Townshend","Roger Daltrey","Rolling Stones",
"Mick Jagger","Keith Richards","Eric Clapton","Jimmy Buffett","Neil Young",
"Bruce Springsteen","Billy Joel","Elton John","Rod Stewart","Phil Collins",
"Peter Gabriel","Sting Sumner","Steven Tyler","Axl Rose","Slash Hudson",
"Kurt Cobain","Dave Grohl","Eddie Vedder","Chris Cornell","Layne Staley",
"Trent Reznor","Marilyn Manson","Ozzy Osbourne","Tony Iommi","Robert Smith",
"Morrissey Steven","Thom Yorke","Chris Martin","Liam Gallagher","Noel Gallagher",
"Damon Albarn","Björk Guðmundsdóttir","Annie Lennox","Dave Matthews","John Mayer",
"Jason Mraz","Jack Johnson","Norah Jones","Alicia Keys","John Legend",
"Usher Raymond","Chris Brown","Trey Songz","Ne-Yo Smith","The Weeknd Tesfaye",
"Frank Ocean","Childish Gambino","Anderson Paak","SZA Rowe","Doja Cat",
"Halsey Frangipane","Lorde Yelich","Sia Furler","Sabrina Carpenter","Charlie Puth",
"Shawn Mendes","Niall Horan","Zayn Malik","Camila Cabello","Fifth Harmony",
"Backstreet Boys","NSYNC Timberlake","Spice Girls","Destiny's Child","TLC Group",
"Boyz II Men","Alicia Keys","India Arie","Erykah Badu","Lauryn Hill",
"Wyclef Jean","Fugees Group","Outkast Duo","Andre 3000","Big Boi Patton",
"Wu-Tang Clan","Method Man","RZA Diggs","GZA Woods","Ghostface Killah",
"Ice Spice Gaston","Megan Thee Stallion","Latto Sherrod","City Girls Group","GloRilla Woods",
"Simon Garfunkel","Art Garfunkel","James Taylor","Carole King","Carly Simon",
"Joni Mitchell","Joan Baez","Peter Paul Mary","Crosby Stills Nash","Graham Nash",
"David Crosby","Stephen Stills","Jackson Browne","Linda Ronstadt","Emmylou Harris",
"Gram Parsons","Gene Clark","Roger McGuinn","John Fogerty","Creedence Clearwater",
"Grace Slick","Janis Joplin","Jerry Garcia","Bob Weir","Phil Lesh",
"Frank Zappa","Captain Beefheart","Lou Reed","John Cale","Nico Christa",
"Iggy Pop","Patti Smith","Television Verlaine","Talking Heads","David Byrne",
"Blondie Harry","Debbie Harry","The Ramones","Joey Ramone","Sex Pistols",
"Johnny Rotten","Sid Vicious","The Clash","Joe Strummer","Mick Jones",
"Elvis Costello","Joe Jackson","Nick Lowe","Squeeze Difford","Ian Dury",
"Peter Gabriel","Genesis Collins","Phil Collins","Yes Anderson","Jon Anderson",
"Rick Wakeman","King Crimson","Robert Fripp","Emerson Lake Palmer","Keith Emerson",
"Jethro Tull","Ian Anderson","Deep Purple","Ritchie Blackmore","Ian Gillan",
"Judas Priest","Rob Halford","Iron Maiden","Bruce Dickinson","Steve Harris",
"Motorhead Lemmy","Lemmy Kilmister","Metallica James","James Hetfield","Lars Ulrich",
"Kirk Hammett","Megadeth Mustaine","Dave Mustaine","Slayer Araya","Tom Araya",
"Anthrax Belladonna","Joey Belladonna","Pantera Anselmo","Phil Anselmo","Dimebag Darrell",
"System of a Down","Serj Tankian","Tool Keenan","Maynard Keenan","Korn Davis",
"Jonathan Davis","Limp Bizkit Durst","Fred Durst","Linkin Park Bennington","Chester Bennington",
"Mike Shinoda","Deftones Moreno","Chino Moreno","Rage Against Machine","Zack de la Rocha",
"Tom Morello","Foo Fighters Grohl","Weezer Cuomo","Rivers Cuomo","Green Day Armstrong",
"Billie Joe Armstrong","Blink 182","Travis Barker","Mark Hoppus","Sum 41 Whibley",
"My Chemical Romance","Gerard Way","Fall Out Boy","Patrick Stump","Pete Wentz",
"Panic at the Disco","Brendon Urie","Paramore Williams","Hayley Williams","Evanescence Amy Lee",
"Flyleaf Boggs","Within Temptation","Nightwish Turunen","Tarja Turunen","Amy Lee",
"Adele Adkins","Sam Smith","James Blunt","Jamie Cullum","Michael Buble",
"Josh Groban","Andrea Bocelli","Il Divo Group","Susan Boyle","Katherine Jenkins",
]

fictional_names = [
"Mickey Mouse","Bugs Bunny","Donald Duck","Daffy Duck","Homer Simpson",
"Bart Simpson","Peter Griffin","SpongeBob SquarePants","Popeye Sailor","Woody Woodpecker",
"Fred Flintstone","Scooby Doo","Tom Cat","Jerry Mouse","Wile E Coyote",
"Road Runner Bird","Yogi Bear","Charlie Brown","Snoopy Dog","Garfield Cat",
"Winnie the Pooh","Tigger Tiger","Peter Pan","Alice Wonderland","Snow White",
"Cinderella Princess","Sleeping Beauty","Belle Princess","Ariel Mermaid","Jasmine Princess",
"Mulan Warrior","Elsa Frozen","Anna Frozen","Simba Lion","Aladdin Prince",
"Buzz Lightyear","Woody Pride","Shrek Ogre","Donkey Talking","Puss Boots",
"Harry Potter","Hermione Granger","Ron Weasley","Albus Dumbledore","Severus Snape",
"Frodo Baggins","Gandalf Grey","Aragorn Elessar","Legolas Greenleaf","Gollum Smeagol",
"Luke Skywalker","Han Solo","Princess Leia","Darth Vader","Obi-Wan Kenobi",
"Yoda Master","Chewbacca Wookiee","James Bond","Jason Bourne","Indiana Jones",
"Ethan Hunt","John McClane","Rocky Balboa","John Rambo","Terminator Robot",
"RoboCop Murphy","Batman Wayne","Superman Kent","Spider-Man Parker","Iron Man Stark",
"Captain America","Thor Odinson","Hulk Banner","Black Widow Romanoff","Wonder Woman Prince",
"The Flash Allen","Green Lantern Jordan","Aquaman Curry","Wolverine Logan","Deadpool Wilson",
"Joker Clown","Lex Luthor","Darth Maul","Voldemort Riddle","Sauron Dark",
"Freddy Krueger","Jason Voorhees","Michael Myers","Hannibal Lecter","Norman Bates",
"Dracula Count","Frankenstein Monster","Sherlock Holmes","Doctor Watson","Hercule Poirot",
"Miss Marple","Nancy Drew","Tarzan Ape","Zorro Masked","Robin Hood",
"Little Red Riding Hood","Jack Beanstalk","Pinocchio Puppet","Peter Rabbit","Winnie Pooh",
"Paddington Bear","Mary Poppins","Willy Wonka","Charlie Bucket","Matilda Wormwood",
"James Giant","Gonzo Muppet","Kermit Frog","Miss Piggy","Fozzie Bear",
"Big Bird Sesame","Elmo Muppet","Cookie Monster","Oscar Grouch","Bert Sesame",
"Ernie Sesame","Optimus Prime","Bumblebee Autobot","Megatron Decepticon","He-Man Warrior",
"Skeletor Villain","She-Ra Princess","GI Joe","Cobra Commander","Master Chief Spartan",
"Lara Croft","Mario Plumber","Luigi Plumber","Princess Peach","Bowser Koopa",
"Link Hero","Zelda Princess","Sonic Hedgehog","Pikachu Pokemon","Ash Ketchum",
"Naruto Uzumaki","Goku Saiyan","Vegeta Prince","Luffy Straw","Sailor Moon",
"Astro Boy","Speed Racer","Inspector Gadget","Bender Robot","Rick Sanchez",
"Morty Smith","Stewie Griffin","Lois Griffin","Marge Simpson","Lisa Simpson",
"Walter White","Tony Soprano","Don Draper","Michael Scott","Dwight Schrute",
"Jack Sparrow","Will Turner","Elizabeth Swann","Captain Hook","Peter Quill",
"Rocket Raccoon","Groot Tree","Star-Lord Quill","Doctor Strange","Black Panther",
"Wanda Maximoff","Vision Android","Ant-Man Lang","Hawkeye Barton","Nick Fury",
"Professor Xavier","Magneto Lehnsherr","Cyclops Summers","Jean Grey","Storm Munroe",
"Beast McCoy","Rogue Anna","Gambit LeBeau","Nightcrawler Wagner","Colossus Rasputin",
"Deadpool Wilson","Punisher Castle","Daredevil Murdock","Elektra Natchios","Kingpin Fisk",
"Green Goblin Osborn","Doctor Octopus","Venom Brock","Mary Jane Watson","Gwen Stacy",
"Aunt May Parker","Uncle Ben Parker","Alfred Pennyworth","Commissioner Gordon","Harvey Dent",
"Catwoman Kyle","Poison Ivy","Harley Quinn","Bane Villain","Ra's al Ghul",
"Two-Face Dent","Riddler Nygma","Penguin Cobblepot","Scarecrow Crane","Robin Grayson",
"Nightwing Grayson","Batgirl Gordon","Lois Lane","Jimmy Olsen","Perry White",
"General Zod","Doomsday Monster","Braniac Villain","Bizarro Clone","Martian Manhunter",
"Cyborg Stone","Shazam Batson","Billy Batson","Green Arrow Queen","Black Canary Lance",
"Zatanna Zatara","Constantine John","Swamp Thing","Hellboy Demon","Spawn Simmons",
"Judge Dredd","Rorschach Kovacs","The Comedian","Doctor Manhattan","Silk Spectre",
"Ozymandias Veidt","Watchmen Group","V Vendetta","Alan Moore Character","John Constantine",
"Wednesday Addams","Gomez Addams","Morticia Addams","Pugsley Addams","Lurch Butler",
"The Grinch","Cindy Lou","Jack Skellington","Sally Ragdoll","Oogie Boogie",
"Edward Scissorhands","Beetlejuice Ghost","Willy Wonka Chocolate","Veruca Salt","Augustus Gloop",
"Violet Beauregarde","Mike Teavee","Grandpa Joe","Fantastic Mr Fox","Mrs Fox",
"James Bond Villain","Blofeld Ernst","Goldfinger Auric","Jaws Villain","Oddjob Henchman",
"Doctor No","Scaramanga Francisco","Rosa Klebb","Miss Moneypenny","Q Branch",
"M Character","Felix Leiter","Vesper Lynd","Pussy Galore","Honey Ryder",
"Ferris Bueller","Cameron Frye","Sloane Peterson","Marty McFly","Doc Brown",
"Biff Tannen","Jennifer Parker","Axel Foley","John Rambo","Rocky Balboa",
"Apollo Creed","Clubber Lang","Ivan Drago","Mickey Goldmill","Paulie Pennino",
]

politicians_names = [
"George Washington","Thomas Jefferson","Abraham Lincoln","Theodore Roosevelt","Franklin Roosevelt",
"John Kennedy","Ronald Reagan","Barack Obama","Bill Clinton","Jimmy Carter",
"Richard Nixon","Dwight Eisenhower","Harry Truman","Woodrow Wilson","William Taft",
"Grover Cleveland","Ulysses Grant","Andrew Jackson","James Madison","James Monroe",
"John Adams","John Quincy Adams","Martin Van Buren","William Harrison","John Tyler",
"James Polk","Zachary Taylor","Millard Fillmore","Franklin Pierce","James Buchanan",
"Andrew Johnson","Rutherford Hayes","James Garfield","Chester Arthur","Benjamin Harrison",
"William McKinley","Warren Harding","Calvin Coolidge","Herbert Hoover","Lyndon Johnson",
"Gerald Ford","George Bush","Bill Clinton","George W Bush","Donald Trump",
"Joe Biden","Winston Churchill","Margaret Thatcher","Tony Blair","David Cameron",
"Theresa May","Boris Johnson","Keir Starmer","Charles de Gaulle","Napoleon Bonaparte",
"Otto von Bismarck","Angela Merkel","Willy Brandt","Konrad Adenauer","Vladimir Lenin",
"Joseph Stalin","Mikhail Gorbachev","Boris Yeltsin","Vladimir Putin","Nikita Khrushchev",
"Mao Zedong","Deng Xiaoping","Xi Jinping","Chiang Kai-shek","Mahatma Gandhi",
"Jawaharlal Nehru","Indira Gandhi","Nelson Mandela","Desmond Tutu","Kwame Nkrumah",
"Julius Nyerere","Haile Selassie","Muammar Gaddafi","Anwar Sadat","Gamal Abdel Nasser",
"Golda Meir","David Ben-Gurion","Yitzhak Rabin","Benjamin Netanyahu","Ayatollah Khomeini",
"Fidel Castro","Che Guevara","Hugo Chavez","Simon Bolivar","Getulio Vargas",
"Juan Peron","Eva Peron","Salvador Allende","Augusto Pinochet","Lula da Silva",
"Justin Trudeau","Stephen Harper","Jean Chretien","Pierre Trudeau","John Diefenbaker",
"Julia Gillard","Kevin Rudd","John Howard","Bob Hawke","Scott Morrison",
"Alexander Hamilton","Benjamin Franklin","Thomas Paine","Patrick Henry","Samuel Adams",
"John Jay","Aaron Burr","Daniel Webster","Henry Clay","John Calhoun",
"Frederick Douglass","Susan B Anthony","Elizabeth Cady Stanton","Rosa Parks","Martin Luther King",
"Malcolm X Little","Booker Washington","W E B Du Bois","John Lewis","Thurgood Marshall",
"Ruth Bader Ginsburg","Sandra Day O'Connor","Sonia Sotomayor","Colin Powell","Condoleezza Rice",
"Madeleine Albright","Hillary Clinton","Kamala Harris","Nancy Pelosi","John McCain",
"Bernie Sanders","Elizabeth Warren","Al Gore","Dan Quayle","Dick Cheney",
"Isaac Newton","Albert Einstein","Charles Darwin","Galileo Galilei","Nicolaus Copernicus",
"Marie Curie","Alexander Graham Bell","Thomas Edison","Nikola Tesla","Benjamin Franklin",
"Leonardo da Vinci","Michelangelo Buonarroti","William Shakespeare","Johann Goethe","Wolfgang Mozart",
"Ludwig Beethoven","Johann Bach","Confucius Sage","Aristotle Philosopher","Plato Philosopher",
"Socrates Philosopher","Julius Caesar","Alexander Great","Cleopatra Queen","Genghis Khan",
"Attila Hun","Charlemagne Emperor","Queen Victoria","Queen Elizabeth","King Henry",
"Catherine Great","Peter Great","Ivan Terrible","Marco Polo","Christopher Columbus",
"Ferdinand Magellan","Vasco da Gama","Amerigo Vespucci","Neil Armstrong","Buzz Aldrin",
"Yuri Gagarin","Sally Ride","John Glenn","Amelia Earhart","Wright Brothers",
"Emmeline Pankhurst","Simone de Beauvoir","Mary Wollstonecraft","Harriet Tubman","Sojourner Truth",
"Nelson Rockefeller","John Rockefeller","Andrew Carnegie","J P Morgan","Henry Ford",
"Cornelius Vanderbilt","Howard Hughes","Walt Disney","Steve Jobs","Bill Gates",
"Warren Buffett","Jeff Bezos","Elon Musk","Mark Zuckerberg","Larry Page",
"Sergey Brin","Tim Berners-Lee","Alan Turing","John von Neumann","Stephen Hawking",
"Richard Feynman","Carl Sagan","Neil deGrasse Tyson","Jane Goodall","Rachel Carson",
"Florence Nightingale","Clara Barton","Jonas Salk","Louis Pasteur","Alexander Fleming",
"Sigmund Freud","Carl Jung","Ivan Pavlov","B F Skinner","Noam Chomsky",
"John Locke","Thomas Hobbes","Jean-Jacques Rousseau","Immanuel Kant","Friedrich Nietzsche",
"Karl Marx","Adam Smith","John Maynard Keynes","Milton Friedman","Max Weber",
"Emile Durkheim","Michel Foucault","Jean-Paul Sartre","Simone Weil","Hannah Arendt",
"Vaclav Havel","Lech Walesa","Pope John Paul","Pope Francis","Dalai Lama",
"Mother Teresa","Desmond Tutu","Elie Wiesel","Anne Frank","Oskar Schindler",
"Raoul Wallenberg","Dietrich Bonhoeffer","Sophie Scholl","Claus von Stauffenberg","Erwin Rommel",
"Dwight Eisenhower","George Patton","Douglas MacArthur","Omar Bradley","Bernard Montgomery",
"Georgy Zhukov","Erich von Manstein","Heinz Guderian","Karl Doenitz","Hermann Goring",
"Adolf Hitler","Benito Mussolini","Francisco Franco","Antonio Salazar","Tojo Hideki",
"Emperor Hirohito","Emperor Meiji","Kublai Khan","Suleiman Magnificent","Akbar Emperor",
"Shah Jahan","Ashoka Emperor","Chandragupta Maurya","Ramses Great","Tutankhamun Pharaoh",
"Hatshepsut Pharaoh","Nefertiti Queen","King Tut","Darius Great","Xerxes King",
"Pericles Athens","Solon Athens","Hammurabi King","Nebuchadnezzar King","Sargon Akkad",
"William Conqueror","Richard Lionheart","Henry Tudor","Elizabeth Tudor","Mary Stuart",
"James Stuart","Charles Stuart","Oliver Cromwell","William Pitt","Robert Peel",
"Benjamin Disraeli","William Gladstone","David Lloyd George","Neville Chamberlain","Clement Attlee",
"Harold Wilson","James Callaghan","John Major","Gordon Brown","Liz Truss",
"Rishi Sunak","Jacinda Ardern","John Key","Helen Clark","Robert Menzies",
"Malcolm Fraser","Paul Keating","Anthony Albanese","Peter Dutton","Pierre Trudeau",
"Brian Mulroney","Kim Campbell","Paul Martin","Stephen Harper","Erin O'Toole",
]

CATEGORIES = {
    "Basketball": {"path": "data/sports/basketball.json", "categories": BASKETBALL, "names": basketball_names},
    "Football": {"path": "data/sports/football.json", "categories": FOOTBALL, "names": football_names},
    "Hockey": {"path": "data/sports/hockey.json", "categories": HOCKEY, "names": hockey_names},
    "Soccer": {"path": "data/sports/soccer.json", "categories": SOCCER, "names": soccer_names},
    "Tennis": {"path": "data/sports/tennis.json", "categories": TENNIS, "names": tennis_names},
    "Combat Sports": {"path": "data/sports/combat_sports.json", "categories": COMBAT, "names": combat_sports_names},
    "Olympics / Track & Field": {"path": "data/sports/olympics_track.json", "categories": OLYMPICS, "names": olympics_track_names},
    "Golf": {"path": "data/sports/golf.json", "categories": GOLF, "names": golf_names},
    "Actors / Actresses": {"path": "data/entertainment/actors.json", "categories": ACTORS, "names": actors_names},
    "Musicians": {"path": "data/entertainment/musicians.json", "categories": MUSICIANS, "names": musicians_names},
    "Fictional Characters": {"path": "data/popculture/fictional.json", "categories": FICTIONAL, "names": fictional_names},
    "Politicians / Historical Figures": {"path": "data/history/politicians_historical.json", "categories": POLITICIANS, "names": politicians_names},
}
